# Generated by Django 3.2.3 on 2022-09-04 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentImportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('domicilie', models.CharField(blank=True, max_length=200, null=True)),
                ('zone', models.CharField(blank=True, max_length=150, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('majoring', models.CharField(blank=True, max_length=150, null=True)),
                ('applied_position', models.CharField(blank=True, max_length=150, null=True)),
                ('experience1', models.CharField(blank=True, max_length=255, null=True)),
                ('experience2', models.CharField(blank=True, max_length=255, null=True)),
                ('experience3', models.CharField(blank=True, max_length=255, null=True)),
                ('software_skill', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'talent_import_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('domicilie', models.TextField(blank=True, null=True)),
                ('sofware_skills', models.TextField(blank=True, default='-', null=True)),
                ('gender', models.BooleanField(choices=[(False, 'MALE'), (True, 'FEMALE')], default=0)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_phoned', models.BooleanField(default=False)),
                ('is_texted', models.BooleanField(default=False)),
                ('is_emailed', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('result', models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'ACCEPTED'), (3, 'IGNORED')], default=1)),
                ('remarks', models.TextField(blank=True, default='-', null=True)),
                ('applied_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.workposition')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.education')),
                ('majoring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.majoring')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.statusperkawinan')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.zone')),
            ],
            options={
                'verbose_name': 'Talent',
                'verbose_name_plural': 'Talents',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('is_present', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.candidate', verbose_name='talent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current_company', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.candidate', verbose_name='Talent')),
            ],
        ),
    ]
