# Generated by Django 3.2.3 on 2022-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='province',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='zone',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Kabupaten'), (2, 'Kota')]),
        ),
    ]
