# Generated by Django 3.2.3 on 2022-08-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_auto_20220827_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Talent', 'verbose_name_plural': 'Talents'},
        ),
    ]
