# Generated by Django 3.2.3 on 2022-08-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('talent', '0004_alter_candidate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='applied_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.workposition'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.education'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='majoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.majoring'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.statusperkawinan'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.zone'),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Majoring',
        ),
        migrations.DeleteModel(
            name='StatusPerkawinan',
        ),
        migrations.DeleteModel(
            name='WorkPosition',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
