# Generated by Django 3.2.3 on 2022-08-27 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0005_auto_20220827_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='interview',
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talent.candidate', verbose_name='talent'),
            preserve_default=False,
        ),
    ]
