# Generated by Django 3.2.3 on 2022-08-27 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0006_auto_20220827_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='experience',
        ),
        migrations.AddField(
            model_name='experience',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talent.candidate', verbose_name='Talent'),
            preserve_default=False,
        ),
    ]
