# Generated by Django 3.2.3 on 2022-10-04 03:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_additionalquestion_religion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0007_auto_20220827_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuestionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=150, verbose_name='Jawaban')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Jenis')),
                ('level', models.CharField(choices=[('1', 'Kurang'), ('2', 'Sedang'), ('3', 'Baik')], max_length=1, verbose_name='Level')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='jenis')),
                ('organizer', models.CharField(max_length=50, verbose_name='penyelenggara')),
                ('venue', models.CharField(max_length=50, verbose_name='Tempat')),
                ('year', models.DateField(verbose_name='Tahun')),
            ],
        ),
        migrations.CreateModel(
            name='EducationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50, verbose_name='Nama Instansi')),
                ('address', models.CharField(max_length=50, verbose_name='Tempat')),
                ('date_graduate', models.IntegerField(verbose_name='Tahun Lulus')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(default='-', verbose_name='Catatan')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bahasa')),
                ('level', models.CharField(choices=[('1', 'Kurang'), ('2', 'Sedang'), ('3', 'Baik')], max_length=1, verbose_name='Level')),
            ],
        ),
        migrations.CreateModel(
            name='Referensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama')),
                ('position', models.CharField(max_length=150, verbose_name='Jabatan/Perusahaan')),
                ('relation', models.CharField(max_length=50, verbose_name='Hubungan')),
                ('phone', models.CharField(max_length=20, verbose_name='No HP')),
            ],
        ),
        migrations.DeleteModel(
            name='TalentImportData',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='domicilie',
            new_name='domicile',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='age',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='education',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='majoring',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='sofware_skills',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='user',
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nama Lengkap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(default='Indonesian', max_length=50, verbose_name='Kewarganegaraan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='no_ktp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. KTP'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ready_on',
            field=models.CharField(default=datetime.datetime(2022, 10, 4, 10, 21, 38, 570927), max_length=50, verbose_name='Bersedia bergabung dalam waktu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.religion', verbose_name='Agama'),
        ),
        migrations.AddField(
            model_name='experience',
            name='resign_reason',
            field=models.CharField(default='New Opportunity', max_length=150, verbose_name='Alasan Keluar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Gaji'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='applied_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.workposition', verbose_name='Posisi yang diinginkan'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.BooleanField(choices=[(False, 'MALE'), (True, 'FEMALE')], default=0, verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='No. Tlp (Rumah & HP)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.statusperkawinan'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referensi',
            name='candidate_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.candidate', verbose_name='Kandidat'),
        ),
        migrations.AddField(
            model_name='language',
            name='candidate_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.candidate', verbose_name='Kandidat'),
        ),
        migrations.AddField(
            model_name='interviewnote',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.interview'),
        ),
        migrations.AddField(
            model_name='interviewnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationlist',
            name='candidate_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.candidate', verbose_name='Kandidat'),
        ),
        migrations.AddField(
            model_name='educationlist',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.education', verbose_name='Tingkat Pendidikan'),
        ),
        migrations.AddField(
            model_name='educationlist',
            name='majoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.majoring', verbose_name='Jurusan'),
        ),
        migrations.AddField(
            model_name='course',
            name='candidate_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.candidate', verbose_name='Kandidat'),
        ),
        migrations.AddField(
            model_name='computerskill',
            name='candidate_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.candidate', verbose_name='Kandidat'),
        ),
        migrations.AddField(
            model_name='addquestionlist',
            name='candidate_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.candidate', verbose_name='Kandidat'),
        ),
        migrations.AddField(
            model_name='addquestionlist',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.additionalquestion', verbose_name='Pertanyaan'),
        ),
    ]
