# Generated by Django 3.2.3 on 2022-10-04 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0008_auto_20221004_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referensi',
            new_name='Reference',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='result',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'ACCEPTED'), (3, 'IGNORED')], default=1, verbose_name='Hasil'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(max_length=150, verbose_name='Nama Perusahaan'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tgl Berakhir'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_current_company',
            field=models.BooleanField(default=False, verbose_name='Masih Bekerja'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=150, verbose_name='Jabatan'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(verbose_name='Tgl Mulai'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.candidate', verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date_time',
            field=models.DateTimeField(verbose_name='Waktu'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='is_present',
            field=models.BooleanField(default=False, verbose_name='Kehadiran'),
        ),
    ]
