# Generated by Django 3.2.3 on 2022-10-05 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0009_auto_20221004_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
