# Generated by Django 3.2.3 on 2022-10-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0010_interview_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addquestionlist',
            old_name='candidate_form',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='computerskill',
            old_name='candidate_form',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='candidate_form',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='educationlist',
            old_name='candidate_form',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='candidate_form',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='candidate_form',
            new_name='candidate',
        ),
    ]
