# Generated by Django 3.2.3 on 2022-10-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0011_auto_20221009_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(verbose_name='Tahun'),
        ),
    ]
