# Generated by Django 3.2.3 on 2022-10-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0012_alter_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
