# Generated by Django 3.2.3 on 2022-10-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0013_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='no_interview',
            field=models.CharField(choices=[('1', 'PERTAMA'), ('2', 'KEDUA')], default='1', max_length=1, verbose_name='Interview yang'),
        ),
    ]
