# Generated by Django 3.2.3 on 2022-10-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_additionalquestion_religion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalquestion',
            options={'verbose_name': 'Pertanyaan Lainnya', 'verbose_name_plural': 'Pertanyaan Lainnya'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Pendidikan', 'verbose_name_plural': 'Pendidikan'},
        ),
        migrations.AlterModelOptions(
            name='majoring',
            options={'verbose_name': 'Jurusan Pendidikan', 'verbose_name_plural': 'Jurusan Pendidikan'},
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'verbose_name': 'Agama', 'verbose_name_plural': 'Agama'},
        ),
        migrations.AlterModelOptions(
            name='statusperkawinan',
            options={'verbose_name': 'Status Perkawinan', 'verbose_name_plural': 'Status Perkawinan'},
        ),
        migrations.AlterModelOptions(
            name='workposition',
            options={'verbose_name': 'Posisi', 'verbose_name_plural': 'Posisi'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Zona', 'verbose_name_plural': 'Zona'},
        ),
    ]
